site_name: RingCentral SDK for Ruby
site_url: https://github.com/grokify/ringcentral-sdk-ruby
repo_url: https://github.com/grokify/ringcentral-sdk-ruby.git
docs_dir: docs
theme: readthedocs
pages:
# Introduction:
- ['index.md', 'About', 'RingCentral SDK']
- ['quickstart.md', 'About', 'Quickstart']

## User Guide:
- ['usage/authorization/Authorization.md', 'User Guide', 'Authorization']
- ['usage/messages/Call-Recordings.md', 'User Guide', 'Call Recordings']
- ['usage/messages/Fax-Messages.md', 'User Guide', 'Fax Messages']
- ['usage/notifications/Subscriptions.md', 'User Guide', 'Subscriptions']