name: Ruby CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.6', '2.7', 'jruby-head', 'ruby-head']
        gemfile: ['Gemfile']
        exclude:
          - ruby: 2.7
            gemfile: activesupport-4.2.x
          - ruby: ruby-head
            gemfile: activesupport-4.2.x
          - ruby: jruby-head
            gemfile: activesupport-4.2.x
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    name: Ruby ${{ matrix.ruby }} with ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
